(function(){
  'use strict';
  const D=DreamData,A=DreamArt,G=GardenBattle,backgrounds=new Map();
  function path(c,r){c.beginPath();r.points.forEach((p,i)=>i?c.lineTo(p.x,p.y):c.moveTo(p.x,p.y));}
  function random(seed){return()=>{seed=(seed*1664525+1013904223)>>>0;return seed/4294967296;};}
  function ground(b){const key=b.index+'-'+!!A.scene;if(backgrounds.has(key))return backgrounds.get(key);const canvas=document.createElement('canvas');canvas.width=D.W;canvas.height=D.H;const c=canvas.getContext('2d'),rng=random(b.index+421);c.fillStyle=b.map.ground;c.fillRect(0,0,D.W,D.H);
    if(A.scene){const w=A.scene.width/5,h=A.scene.height/2;c.drawImage(A.scene,b.index%5*w,Math.floor(b.index/5)*h,w,h,0,0,D.W,D.H);c.fillStyle=b.index===6?'#a8c4c31b':'#fff7e323';c.fillRect(0,0,D.W,D.H);}
    else{for(let i=0;i<850;i++){c.fillStyle=['#fff3d84d','#526e4229','#ddd5a650','#90afb235'][i%4];c.beginPath();c.ellipse(rng()*960,rng()*600,2+rng()*13,1+rng()*5,rng()*3,0,Math.PI*2);c.fill();}}
    c.lineJoin='round';c.lineCap='round';for(const r of b.routes){path(c,r);c.strokeStyle='#526b5930';c.lineWidth=111;c.stroke();path(c,r);c.strokeStyle='#e7d9b7';c.lineWidth=101;c.stroke();path(c,r);c.strokeStyle=b.map.water;c.lineWidth=88;c.stroke();path(c,r);c.strokeStyle='#c4e5e36b';c.lineWidth=65;c.stroke();}
    for(const r of b.routes)for(let s=15;s<r.length;s+=17){const p=G.at(r,s),o=(rng()-.5)*62;c.save();c.translate(p.x,p.y);c.rotate(p.angle);c.strokeStyle=rng()>.5?'#f5ffe873':'#5c9bbd43';c.lineWidth=1+rng()*2;c.beginPath();c.moveTo(-4,o);c.lineTo(5+rng()*9,o+1);c.stroke();c.restore();}
    backgrounds.set(key,canvas);return canvas;
  }
  function lotus(c,x,y,t=0,size=1){c.save();c.translate(x,y);c.scale(size,size);c.fillStyle='#4f7e7455';c.beginPath();c.ellipse(0,20,46,15,0,0,Math.PI*2);c.fill();const glow=c.createRadialGradient(0,-5,4,0,-5,80);glow.addColorStop(0,'#fff7c39c');glow.addColorStop(1,'#fff7c300');c.fillStyle=glow;c.fillRect(-80,-85,160,160);
    for(let row=0;row<2;row++)for(let i=0;i<7;i++){c.save();c.rotate((i-3)*.37);c.translate(0,row?-7:3);c.scale(row?.73:1,row?.87:1);const g=c.createLinearGradient(0,-57,0,15);g.addColorStop(0,'#fffdf0');g.addColorStop(.6,row?'#f3d495':'#ecc698');g.addColorStop(1,'#c79c61');c.fillStyle=g;c.strokeStyle='#fff7dc';c.lineWidth=1;c.beginPath();c.moveTo(0,15);c.bezierCurveTo(-35,-6,-16,-43,0,-60);c.bezierCurveTo(18,-43,35,-6,0,15);c.fill();c.stroke();c.restore();}c.fillStyle='#fff9d3';c.beginPath();c.arc(0,-4,8+Math.sin(t)*.8,0,7);c.fill();c.restore();}
  function hero(c,t,b,clock){const image=A.heroes[D.byId[t.hero].i],level=b.levels[t.hero]||1,size=78;c.save();c.translate(t.x,t.y);c.fillStyle='#3c534326';c.beginPath();c.ellipse(0,5,22,7,0,0,7);c.fill();if(image)c.drawImage(image,-size/2,-size+12+Math.sin(clock*2+t.id)*1,size,size);else{c.fillStyle=D.byId[t.hero].color;c.beginPath();c.arc(0,-20,19,0,7);c.fill();c.fillStyle='#fff8e0';c.beginPath();c.arc(0,-34,17,0,7);c.fill();}
    if(level>=3){c.fillStyle='#f5dfa0';c.beginPath();c.arc(23,-40+Math.sin(clock*2)*3,2.5,0,7);c.fill();}if(level===5){c.strokeStyle='#f5d88888';c.lineWidth=1;c.beginPath();c.ellipse(0,3,26,9,0,0,7);c.stroke();}for(let i=0;i<t.tier;i++){c.fillStyle='#f5e4b2';c.beginPath();c.arc(-5*(t.tier-1)+i*10,13,2.8,0,7);c.fill();}c.restore();}
  function monster(c,e,clock){const d=D.enemies[e.type],image=A.monsters[e.type],size=d.kind==='boss'?62:48;c.save();c.translate(e.x,e.y);c.fillStyle='#243c4b22';c.beginPath();c.ellipse(0,10,size*.27,6,0,0,7);c.fill();c.save();if(Math.cos(e.angle)<0)c.scale(-1,1);if(image)c.drawImage(image,-size/2,-size/2+Math.sin(clock*7+e.id)*.8,size,size);else{c.fillStyle='#4f5743';c.beginPath();c.ellipse(0,0,16,13,0,0,7);c.fill();c.fillStyle='#edd69d';c.fillRect(-7,-6,4,4);c.fillRect(3,-6,6,4);}c.restore();
    const bar=d.kind==='boss'?48:30;c.fillStyle='#20393366';c.fillRect(-bar/2,-size/2-5,bar,4);c.fillStyle='#d78773';c.fillRect(-bar/2,-size/2-5,bar*Math.max(0,e.hp/e.maxHp),4);if(e.shield>0){c.fillStyle='#a3d7de';c.fillRect(-bar/2,-size/2-8,bar*Math.min(1,e.shield/(e.maxHp*.5)),2);}if(e.slowUntil>clock){c.strokeStyle='#d0f8ff';c.lineWidth=1.5;c.beginPath();c.ellipse(0,8,20,6,0,0,7);c.stroke();}if(e.burnUntil>clock){c.fillStyle='#ffc36b';c.beginPath();c.arc(12,-3,3,0,7);c.fill();}c.restore();}
  function draw(canvas,b,selected,aimItem){const c=canvas.getContext('2d');c.setTransform(canvas.width/D.W,0,0,canvas.height/D.H,0,0);c.clearRect(0,0,D.W,D.H);c.drawImage(ground(b),0,0);const clock=b.time;
    for(const r of b.routes){for(let s=140;s<r.length-70;s+=240){const p=G.at(r,s);c.save();c.translate(p.x,p.y);c.rotate(p.angle);c.strokeStyle='#f2ffff70';c.lineWidth=2;c.beginPath();c.moveTo(-4,-4);c.lineTo(1,0);c.lineTo(-4,4);c.stroke();c.restore();}const entry=G.at(r,50);c.save();c.translate(entry.x,entry.y);c.strokeStyle='#e5ffff';c.lineWidth=2;c.beginPath();c.ellipse(0,0,13,23,0,0,7);c.stroke();c.strokeStyle='#527fac';c.lineWidth=8;c.globalAlpha=.45;c.stroke();c.restore();}
    const tower=b.towers.find(t=>t.pad===selected);if(tower){const s=b.stats(tower);c.save();c.fillStyle='#fff7b913';c.strokeStyle='#fff7d4bc';c.lineWidth=1.4;c.setLineDash([7,6]);c.beginPath();c.arc(tower.x,tower.y,s.range,0,7);c.fill();c.stroke();c.restore();}
    for(const p of b.pads){c.save();c.translate(p.x,p.y);c.fillStyle=p.blocked?'#b4c6c6':'#f7ebd6d4';c.strokeStyle=p.id===selected?'#b09055':'#d4c6a7';c.lineWidth=p.id===selected?3:1;c.beginPath();c.ellipse(0,1,25,13,0,0,7);c.fill();c.stroke();if(p.blocked){c.fillStyle='#d9edf1cf';c.strokeStyle='#7da4b4';for(let j=0;j<3;j++){c.beginPath();c.moveTo((j-1)*13-8,0);c.lineTo((j-1)*13-4,-21-j*5);c.lineTo((j-1)*13+5,-8-j*3);c.lineTo((j-1)*13+9,1);c.closePath();c.fill();c.stroke();}if(b.focus===p.id){c.fillStyle='#7b7665';c.font='12px Georgia';c.textAlign='center';c.fillText(Math.ceil(p.hp),0,24);}}else if(!b.towers.some(t=>t.pad===p.id)){c.strokeStyle='#b8a47d';c.lineWidth=2;c.beginPath();c.moveTo(-5,0);c.lineTo(5,0);c.moveTo(0,-5);c.lineTo(0,5);c.stroke();}c.restore();}
    const units=[...b.towers.map(t=>({y:t.y,t})),...b.enemies.map(e=>({y:e.y,e}))].sort((a,b)=>a.y-b.y);for(const u of units)u.t?hero(c,u.t,b,clock):monster(c,u.e,clock);
    const end=G.at(b.routes[0],b.routes[0].length);lotus(c,end.x,end.y,clock,.78);c.fillStyle='#f9f5dedb';c.fillRect(end.x-36,end.y-68,72,8);c.fillStyle='#89ae7a';c.fillRect(end.x-34,end.y-66,68*b.hp/10,4);if(b.flowerShield){c.strokeStyle='#e4f5d5';c.lineWidth=2;c.beginPath();c.arc(end.x,end.y-12,47,Math.PI,Math.PI*2);c.stroke();}
    for(const p of b.projectiles){c.fillStyle=p.color;c.beginPath();c.arc(p.x,p.y,p.kind==='heavy'?5:3.5,0,7);c.fill();c.fillStyle='#fff4ce';c.beginPath();c.arc(p.x-1,p.y-1,1.5,0,7);c.fill();}
    for(const f of b.fx){c.save();c.globalAlpha=Math.min(1,f.life/f.max);if(f.kind==='beam'){c.strokeStyle=f.color;c.lineWidth=5;c.beginPath();c.moveTo(f.x,f.y);c.lineTo(f.ex,f.ey);c.stroke();c.strokeStyle='#fff5d1';c.lineWidth=1.4;c.stroke();}else if(f.kind==='ring'){c.strokeStyle=f.color;c.lineWidth=3;c.beginPath();c.arc(f.x,f.y,Math.max(1,f.r*(1-f.life/f.max)),0,7);c.stroke();}else if(f.kind==='flame'){c.translate(f.x,f.y);c.rotate(f.angle);const g=c.createLinearGradient(0,0,f.r,0);g.addColorStop(0,'#fff2a6bd');g.addColorStop(1,'#ed8b4b00');c.fillStyle=g;c.beginPath();c.moveTo(0,0);c.arc(0,0,f.r,-.65,.65);c.closePath();c.fill();}c.restore();}
    if(aimItem){c.fillStyle='#ffecbb';c.strokeStyle='#986e32';c.font='16px KaiTi,serif';c.textAlign='center';c.fillText('点击蓝色河道投下星火瓶',480,575);}
  }
  window.GardenRenderer={draw,lotus};
})();
