(()=>{'use strict';
const E=window.Odyssey,$=s=>document.querySelector(s),key='peijia-odyssey-v1';let state=null,saved=null,home=true,selected=-1,page=0,choice=-1,lastCard=null,storageOK=true,busy=false,queuedEnemy=false,enemyTimer=null;
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
try{const parsed=JSON.parse(localStorage.getItem(key));if(E.valid(parsed))saved=parsed;}catch{storageOK=false;}
function save(){try{localStorage.setItem(key,JSON.stringify(state));saved=JSON.parse(JSON.stringify(state));}catch{storageOK=false;}}
function scene(id,alt){return '<img class="scene-image" src="../../images/odyssey-'+id+'.jpg" alt="'+alt+'">';}
// Original card illustrations, rendered as clipped views without altering source files.
const crops={ram:['04-reward',153,665,150,207],ship:['04-reward',312,657,142,203],spear:['04-reward',473,671,143,205],shield:['03-victory',538,1053,129,166],nectar:['03-victory',173,1042,134,160],thunder:['03-victory',299,1005,123,177]};
function art(id){const [file,x,y,w,h]=crops[id];return `<svg viewBox="${x} ${y} ${w} ${h}" preserveAspectRatio="xMidYMid slice" aria-hidden="true"><image href="../../images/odyssey-${file}.jpg" width="768" height="1376"/></svg>`;}
function pauseAuto(){if(enemyTimer!==null)clearTimeout(enemyTimer);enemyTimer=null;busy=false;}
function show(content){pauseAuto();$('#close-dialog').textContent='明白了，返回游戏';$('#dialog-content').innerHTML=content;if(!$('#dialog').open)$('#dialog').showModal();}
function close(){if($('#dialog').open)$('#dialog').close();scheduleEnemy();}
function announce(t){$('#announcement').textContent=t;}

function codex(){show('<h2 id="dialog-title">卡牌图鉴 · 全部 6 种</h2><p>初始牌组共 12 张：长矛、盾牌各 3 张；公羊、战船各 2 张；甘露、雷电各 1 张。每回合抽 5 张，手牌区每页展示 3 张。</p><div class="codex">'+Object.entries(E.cards).map(([id,c])=>'<article>'+art(c.art)+'<div><h3>'+c.name+' <small>'+c.cost+' 行动力 · '+c.kind+'</small></h3><p>'+c.text+'</p><p class="tip">'+({spear:'低费补刀，或配合防御牌使用。',ram:'集中攻击；留意敌人的护盾，避免浪费伤害。',shield:'敌人准备重击时优先使用，护盾可以叠加。',ship:'防御同时补牌，适合寻找攻击或治疗。',nectar:'受伤后再使用，生命不会超过上限。',thunder:'同时攻防，适合迎接敌人的攻击。'}[id])+'</p></div></article>').join('')+'</div><p>祝福会增强实际数值，战斗中点牌查看当前效果。</p>');}
function guide(){show('<h2 id="dialog-title">直接出牌，自动交锋</h2><p>目标：闯过 3 段航程，打败最后的波塞冬。</p><ol><li>START 后先到航程地图。地图会标出已完成、当前可挑战、暂未解锁的关卡。</li><li>战斗中直接点底部卡牌出招，牌面写着费用与技能。行动力用完或没有可出的牌，对手会自动攻击。</li><li>对手出招后，行动力自动补满，并抽到 5 张牌。无需点击结束或确认。</li><li>敌人下一击会提前显示。可用护盾抵挡，也可点「举盾等待」把每点剩余行动力变成 2 点护盾。</li><li>前两关胜利后选 1 个祝福，奖励会带回地图，并影响下一关。</li></ol><button data-action="codex">查看全部 6 种卡牌</button><p>键盘 1–3 直接出牌，E 举盾等待，Esc 打开菜单。图鉴和菜单打开时战斗暂停。</p>');}
function scheduleEnemy(){if(home||!state||state.status!=='battle'||busy||$('#dialog').open||document.hidden)return;if(!queuedEnemy&&state.hand.some(id=>E.cards[id].cost<=state.energy))return;queuedEnemy=true;busy=true;const strip=$('.intent-strip');if(strip)strip.innerHTML='<strong>对手正在出招…</strong><span>'+E.stages[state.stage].enemy+' · '+E.intent(state).label+'</span>';enemyTimer=setTimeout(()=>{enemyTimer=null;if(home||document.hidden||$('#dialog').open){busy=false;return;}const before=state.hp,move=E.intent(state),blocked=Math.min(state.block,move.attack);E.endTurn(state);busy=false;queuedEnemy=false;selected=-1;page=0;lastCard=null;save();render();if(state.status==='battle'){const message='对手攻击 '+move.attack+' · 抵挡 '+blocked+' · 受伤 '+(before-state.hp)+' → 行动力已恢复';const strip=$('.intent-strip');if(strip)strip.innerHTML='<strong>轮到你出牌</strong><span>'+message+'</span>';$('#phone').classList.add('flash');announce(message);}},750);}

function menu(){show('<h2 id="dialog-title">航行菜单</h2><p>'+(!home?'航程已保存。暂停期间不会发生战斗。':'点击原画中的 START 开始航程。')+'</p>'+(!home&&state?'<button data-action="map">航程地图</button>':'')+'<button data-action="guide">玩法说明</button><button data-action="codex">卡牌图鉴</button><button data-action="home">回到启航画面</button><button data-action="restart">重新启航</button><p><a href="index.html" target="_blank" rel="noopener">在独立页面中游玩 ↗</a></p>');}
function title(){home=true;$('#controls').className='controls';pauseAuto();queuedEnemy=false;close();$('#phone').className='phone';$('#phone').innerHTML=scene('01-title','奥德赛原作启航界面：星夜战船、英雄卡牌与 START')+'<button class="hotspot start-hit" data-action="begin" aria-label="START · 开始或继续航行"></button>';
$('#controls').innerHTML='<p><strong>点击画面里的 START，'+(saved&&!['victory','defeat'].includes(saved.status)?'继续你的航程':'扬帆启航')+'。</strong></p><div class="control-row"><button data-action="guide">玩法说明</button><small>原作竖屏画面 · 三段航程</small><a href="index.html" target="_blank" rel="noopener">独立窗口 ↗</a></div>';}
function start(){pauseAuto();queuedEnemy=false;state=E.create();state.status='map';state.uiScreen='map';state.stage=state.completed||0;state.hand=[];state.deck=[];state.discard=[];save();page=0;selected=-1;lastCard=null;close();render();}
function begin(){if(saved&&!['victory','defeat'].includes(saved.status)){state=JSON.parse(JSON.stringify(saved));render();}else start();}
function restart(){if(saved&&!['victory','defeat'].includes(saved.status)){show('<h2 id="dialog-title">重新启航？</h2><p>这会替换当前航程。想保留进度可以返回游戏继续。</p><button data-action="new">确认重新开始</button>');}else start();}
function cardText(c){return c.text.replace(/造成 (\d+) 点伤害/,(_,n)=>'造成 '+(Number(n)+state.bonus)+' 点伤害');}
function render(){home=false;$('#controls').className='controls';$('#phone').className='phone';if(state.status==='defeat'){defeat();return;}if(state.status==='map'){map();return;}if(state.status==='complete'){complete();return;}if(state.status!=='battle'){if(state.uiScreen==='reward')rewards();else victory();return;}battle();scheduleEnemy();}
function map(){pauseAuto();queuedEnemy=false;const completed=state.completed||0,unlocked=state.unlocked||1;state.uiScreen='map';$('#phone').innerHTML=scene('01-title','奥德赛原作启航界面：星夜战船、英雄卡牌与 START')+'<section class="map-panel" aria-label="航程地图"><p>航程地图</p><h2>奥德修斯的三段归乡路</h2><div class="map-line" aria-hidden="true"></div>'+E.stages.map((st,i)=>{const done=i<completed,current=i===completed&&i<unlocked,locked=i>=unlocked;return '<button class="map-node '+(done?'done ':current?'current ':'locked ')+'" data-stage="'+i+'" '+(!current?'disabled':'')+' aria-label="'+(done?'已完成':current?'进入':'未解锁')+'第 '+(i+1)+' 关，'+esc(st.name)+'"><span>'+(i+1)+'</span><strong>'+esc(st.name)+'</strong><small>'+(done?'已通过 · 祝福已生效':current?'点击进入战斗':locked?'完成上一关后解锁':'')+'</small></button>';}).join('')+'</section>';$('#controls').innerHTML='<p><strong>'+(completed>=3?'三段航程全部完成。':'选择发光的航线进入第 '+(completed+1)+' 关。')+'</strong><br>'+(state.relics.length?'已获得祝福：'+state.relics.map(esc).join('、')+'。':'前两关胜利后可选择祝福，带进下一关。')+'</p><div class="control-row"><button data-action="guide">玩法说明</button><button data-action="codex">卡牌图鉴</button><button data-action="restart">重新启航</button></div>';}
function selectStage(i){if(!state||!E.start(state,i))return;state.uiScreen='battle';page=0;selected=-1;choice=-1;lastCard=null;save();render();}
function battle(){const s=state,move=E.intent(s);page=Math.min(page,Math.max(0,Math.ceil(s.hand.length/3)-1));const hand=s.hand.slice(page*3,page*3+3);$('#phone').innerHTML=scene('02-battle','奥德赛原作竖屏战斗界面：血条、回合卷轴、公羊战场和底部手牌')+`<div class="health-live player" role="meter" aria-label="英雄生命" aria-valuenow="${s.hp}" aria-valuemin="0" aria-valuemax="${s.maxHP}"><i style="width:${s.hp/s.maxHP*100}%"></i></div><span class="hp-number player">${s.hp} / ${s.maxHP} · 盾 ${s.block}</span><div class="health-live enemy" role="meter" aria-label="敌人生命" aria-valuenow="${s.enemyHP}" aria-valuemin="0" aria-valuemax="${s.enemyMax}"><i style="width:${s.enemyHP/s.enemyMax*100}%"></i></div><span class="hp-number enemy">${s.enemyHP} / ${s.enemyMax} · 盾 ${s.enemyBlock}</span><span class="turn-live" aria-label="第 ${s.stage+1} 关"><small>航程</small>${s.stage+1} / 3</span><button class="hotspot pause-hit" data-action="menu" aria-label="PAUSE · 暂停游戏"></button><div class="intent-strip"><strong>${E.stages[s.stage].enemy}</strong><span>下一步：攻击 ${move.attack}${move.block?' / 护盾 '+move.block:''}</span></div><div class="deck-readout">第 ${s.stage+1} / 3 段航程<b>${s.deck.length}</b>抽牌堆 · 弃牌 ${s.discard.length}</div>${lastCard?'<div class="last-play">'+art(E.cards[lastCard].art)+'<span>'+E.cards[lastCard].name+'</span></div>':''}<button class="hotspot turn-hit" data-action="brace" aria-label="举盾等待对手攻击">举盾等待<small>剩余行动力 → 护盾</small></button><div class="energy-readout">行动力 <b>${s.energy} / ${s.maxEnergy}</b><br>直接点牌出招 · 用完自动交锋</div>${hand.map((id,i)=>{const c=E.cards[id],index=page*3+i;return '<button class="hand-slot'+(index===selected?' selected':'')+'" data-slot="'+i+'" data-card="'+index+'" '+(c.cost>s.energy?'data-unaffordable="true"':'')+' aria-label="'+c.name+'，消耗 '+c.cost+' 行动力，'+cardText(c)+'" aria-pressed="'+(index===selected)+'">'+art(c.art)+'<span class="cost">'+c.cost+'</span><span class="card-label">'+c.name+'<small>'+cardText(c)+'</small></span></button>';}).join('')}${!hand.length?'<div class="empty-slot">对手即将攻击…<br>正在准备新手牌</div>':''}`;battleControls();}
function battleControls(){$('#controls').className='controls compact';const s=state;$('#controls').innerHTML='<span>点牌出招 · 用完自动交锋</span><button data-action="page" '+(s.hand.length<=3?'disabled':'')+'>手牌 '+(page+1)+' / '+Math.max(1,Math.ceil(s.hand.length/3))+'　换一组 →</button>';const visible=s.hand.slice(page*3,page*3+3);if(!visible.some(id=>E.cards[id].cost<=s.energy)&&s.hand.some(id=>E.cards[id].cost<=s.energy)){page=Math.floor(s.hand.findIndex(id=>E.cards[id].cost<=s.energy)/3);battle();}}
function victory(){$('#controls').className='controls';const s=state;$('#phone').innerHTML=scene('03-victory','奥德赛原作胜利界面：战船、公羊、战果卷轴与奖励卡牌')+[['累计伤害',s.damage],['获得祝福',s.relics.length],['战斗回合',s.totalTurns],['通过关卡',s.stage+1]].map((r,i)=>'<div class="victory-stat row'+i+'"><span>'+r[0]+'</span><b>'+r[1]+'</b></div>').join('')+'<button class="hotspot victory-next" data-action="treasure" aria-label="前往奖励界面"><span>前往领奖 →</span></button>';$('#controls').innerHTML='<p><strong>'+E.stages[s.stage].enemy+'的试炼已完成。</strong><br>点击画面底部的奖励卡牌，打开你的宝箱。</p>';}
function rewardPreview(i){const s=state;return ['攻击加成：+'+s.bonus+' → +'+(s.bonus+2)+'；修船后生命 '+Math.min(s.maxHP,s.hp+10)+' / '+s.maxHP,'生命上限 '+s.maxHP+' → '+(s.maxHP+8)+'；治疗后生命 '+Math.min(s.maxHP+8,s.hp+22)+' / '+(s.maxHP+8),'每回合行动力 '+s.maxEnergy+' → '+(s.maxEnergy+1)+'；修船后生命 '+Math.min(s.maxHP,s.hp+10)+' / '+s.maxHP][i];}
function rewards(){$('#controls').className='controls';const s=state;$('#phone').innerHTML=scene('04-reward','奥德赛原作宝箱界面：金币、宝石、公羊战船长矛奖励牌与 CLAIM REWARD')+[0,1,2].map(i=>'<button class="hotspot reward-hit'+(choice===i?' chosen':'')+'" data-choice="'+i+'" aria-label="选择'+E.rewards[i].name+'：'+E.rewards[i].text+'" aria-pressed="'+(choice===i)+'"></button>').join('')+'<div class="reward-note"><strong>Gold: 500　Gems: 20</strong><small>'+(choice<0?'选择一张卡牌祝福':esc(E.rewards[choice].name))+'</small></div><button class="hotspot claim-hit" data-action="claim" aria-label="CLAIM REWARD · 领取奖励" '+(choice<0?'disabled':'')+'></button>';$('#controls').innerHTML='<p><strong>'+(choice<0?'点选画面中的公羊、战船或长矛卡牌。':E.rewards[choice].name)+'</strong><br>'+(choice<0?'选择一份祝福，再点击 CLAIM REWARD。':(s.status==='reward'?E.rewards[choice].text:'所选卡牌作为本次归乡纪念。')+(s.status==='reward'?' '+rewardPreview(choice)+'。领取后回到航程地图。':' 点击 CLAIM REWARD，完成本次航程。'))+'</p><small>前两关：500 金币用于修船恢复 10 生命，20 宝石兑换所选祝福；下一关会在地图上解锁。最终关领取归乡纪念奖励。</small>';}
function complete(){$('#controls').className='controls';$('#phone').innerHTML=scene('03-victory','奥德赛原作胜利界面：战船、公羊、战果卷轴与奖励卡牌')+[['累计伤害',state.damage],['获得祝福',state.relics.length],['战斗回合',state.totalTurns],['通过关卡',3]].map((r,i)=>'<div class="victory-stat row'+i+'"><span>'+r[0]+'</span><b>'+r[1]+'</b></div>').join('')+'<button class="hotspot victory-next" data-action="map" aria-label="返回航程地图"><span>返回地图 →</span></button>';$('#controls').innerHTML='<p><strong>伊萨卡，终于到了。</strong><br>三段航程全部完成。归乡纪念奖励：500 金币 · 20 宝石。</p><div class="control-row"><button data-action="map">航程地图</button><button data-action="new">再启航一次</button><button data-action="home">回到封面</button></div>';}
function defeat(){title();home=false;show('<h2 id="dialog-title">这一次，先在海岸休息。</h2><p>你在'+E.stages[state.stage].name+'耗尽了生命。下次留意敌人的重击回合，用盾牌或战船提前防守。</p><p>累计伤害 '+state.damage+' · 战斗回合 '+state.totalTurns+'</p><button data-action="new">重新启航</button><button data-action="home">回到封面</button>');}
function play(){if(!state||state.status!=='battle'||home||busy)return;const id=state.hand[selected];if(!id)return;const hp=state.enemyHP;if(E.play(state,selected)){lastCard=id;selected=-1;if(state.status!=='battle')state.uiScreen='victory';save();render();announce(state.log[0]);if(state.status==='battle'){const hit=hp-state.enemyHP;$('#phone').classList.add('flash');if(hit){const n=document.createElement('span');n.className='battle-float';n.textContent='−'+hit;$('#phone').append(n);}}}}
function action(a){if(a==='menu')return menu();if(a==='guide')return guide();if(a==='codex')return codex();if(a==='home')return title();if(a==='restart')return restart();if(a==='new')return start();if(a==='begin')return begin();if(a==='map'&&state){if($('#dialog').open)$('#dialog').close();state.status='map';state.uiScreen='map';save();return render();}if(home||!state||$('#dialog').open||busy)return;if(a==='play')return play();if(a==='brace'&&state.status==='battle'&&!busy){state.block+=state.energy*2;state.energy=0;state.log.unshift('举盾等待 · 剩余行动力已转为护盾');save();render();}if(a==='page'&&state.status==='battle'){page=(page+1)%Math.max(1,Math.ceil(state.hand.length/3));selected=-1;battle();}if(a==='treasure'&&['reward','victory'].includes(state.status)){state.uiScreen='reward';choice=-1;save();rewards();}if(a==='claim'&&state.uiScreen==='reward'&&choice>=0){if(state.status==='reward'){E.reward(state,choice);state.uiScreen='map';selected=-1;choice=-1;page=0;lastCard=null;save();render();}else if(state.status==='victory'&&!state.claimed){state.claimed=true;state.gold=500;state.gems=20;state.completed=3;state.unlocked=3;state.status='complete';state.uiScreen='complete';save();show('<h2 id="dialog-title">伊萨卡，终于到了。</h2><p>你完成了三段航程。奥德修斯与船员们穿过风暴，平安归乡。</p><p>归乡纪念奖励：500 金币 · 20 宝石<br>前两关的金币与宝石已用于修船和兑换祝福<br>累计伤害 '+state.damage+' · 战斗回合 '+state.totalTurns+'</p><button data-action="map">查看航程地图</button><button data-action="new">再启航一次</button><button data-action="home">回到封面</button>');complete();}}}
document.addEventListener('click',e=>{const a=e.target.closest('[data-action]'),stage=e.target.closest('[data-stage]'),card=e.target.closest('[data-card]'),r=e.target.closest('[data-choice]');if(a)return action(a.dataset.action);if(stage&&!stage.disabled)return selectStage(Number(stage.dataset.stage));if(home||$('#dialog').open||!state||busy)return;if(card&&state.status==='battle'){selected=Number(card.dataset.card);if(E.cards[state.hand[selected]].cost>state.energy){announce('这张牌费用不足，可以选择其他牌或举盾等待');const strip=$('.intent-strip');if(strip)strip.innerHTML='<strong>这张牌费用不足</strong><span>请选择低费牌，或举盾等待对手攻击</span>';}else play();}if(r&&state.uiScreen==='reward'){choice=Number(r.dataset.choice);rewards();}});
$('#menu').onclick=menu;$('#codex-button').onclick=codex;$('#close-dialog').onclick=close;document.addEventListener('keydown',e=>{if(e.key==='Escape'){if(!$('#dialog').open){e.preventDefault();menu();}return;}if(home||$('#dialog').open||e.repeat||e.ctrlKey||e.altKey||e.metaKey||/INPUT|TEXTAREA|SELECT/.test(e.target.tagName))return;if(e.key.toLowerCase()==='e'){e.preventDefault();action('brace');}if(/^[1-3]$/.test(e.key)){const c=$('[data-slot="'+(Number(e.key)-1)+'"]');if(c&&!c.disabled){e.preventDefault();c.click();}}});document.addEventListener('visibilitychange',()=>{if(document.hidden&&!home&&!$('#dialog').open)menu();});addEventListener('pagehide',pauseAuto);title();
})();
