(()=>{'use strict';
 const E=window.SpiritEngine,$=id=>document.getElementById(id),canvas=$('game'),ctx=canvas.getContext('2d'),KEY='portfolio.spirit-roam.v1';
 let assets,motionRenderer,lobbyMotion,heroMotion,game,save,storageOK=true,raf=0,last=0,accumulator=0,camera={x:0,y:280},selected='03',mode='home',input={left:false,right:false,down:false,attack:false},heldKeys=new Set(),touchPoints=new Map(),queued={jump:false,attack:false},particles=[],toastTimer,runRecorded=false,VW=1280,VH=720;
 function portraitPhone(){let width=innerWidth,height=innerHeight;try{width=window.top.innerWidth;height=window.top.innerHeight;}catch{}return matchMedia('(pointer:coarse)').matches&&height>width;}
 function resize(){VW=1280;VH=720;canvas.width=VW;canvas.height=VH;const rotate=$('rotate-dialog');if(portraitPhone()){if(mode==='play')pause();if(!rotate.open)rotate.showModal();}else if(rotate.open)rotate.close();if(game){camera.x=Math.max(0,Math.min(game.level.width-VW,game.player.x-VW*.28));camera.y=Math.max(-320,Math.min(370,game.player.y-VH*.6));draw();}}
 window.addEventListener('resize',resize);resize();
 try{save=E.cleanSave(JSON.parse(localStorage.getItem(KEY)));}catch{save=E.cleanSave(null);}selected=save.hero;
 const fmt=s=>`${String(Math.floor(s/60)).padStart(2,'0')}:${String(Math.floor(s%60)).padStart(2,'0')}`;
 function persist(){save.hero=selected;try{localStorage.setItem(KEY,JSON.stringify(save));}catch{storageOK=false;toast('浏览器暂时无法保存进度，本次仍可继续游玩。');}}
 function toast(text){$('toast').textContent=text;$('toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('show'),2600);}
 function sound(type){window.SpiritAudio.fx(type);}
 function soundButtons(){document.querySelectorAll('.sound-toggle').forEach(b=>{b.textContent=save.sound?'♫':'♪';b.setAttribute('aria-label',save.sound?'关闭音效':'开启音效');b.setAttribute('aria-pressed',String(save.sound));});}
 function choose(id){finishOpening();selected=id;const h=E.HEROES.find(h=>h.id===id);$('featured').dataset.hero=id;$('featured').style.setProperty('--entry-order',E.HEROES.findIndex(h=>h.id===id));$('featured').hidden=false;$('featured').setAttribute('aria-label',h.name+'角色形象');$('featured').classList.remove('arrive');void $('featured').offsetWidth;$('featured').classList.add('arrive');$('featured-number').textContent='NO. '+id;$('featured-name').textContent=h.name;$('featured-line').textContent=h.line;document.querySelectorAll('.hero-card').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.hero===id)));buildParty();lobbyMotion?.select(id);persist();}
 function finishOpening(){lobbyMotion?.skip();}
 function opening(){lobbyMotion?.start();}
 function buildHeroes(){const host=$('hero-picker');host.textContent='';E.HEROES.forEach((h,i)=>{const b=document.createElement('button');b.className='hero-card';b.dataset.hero=h.id;b.style.setProperty('--i',i);b.setAttribute('aria-label','选择'+h.name);b.innerHTML=`<small>${h.id}</small><img alt="" src="${assets.urls[h.id]}"><strong>${h.name}</strong>`;b.onclick=()=>choose(h.id);host.append(b);});choose(selected);}
 function updateProgress(){const total=save.records.reduce((s,r)=>s+(r?.stars||0),0);$('journey-progress').textContent=`六关全部开放 · 已收集 ${total} / 18 颗旅途之星`;}
 function showMap(){mapReturn=mode;mode='map';const grid=$('level-grid');grid.textContent='';E.META.forEach((m,i)=>{const r=save.records[i],b=document.createElement('button');b.className='level-card';b.setAttribute('aria-label',`${i+1} ${m[0]}`);b.innerHTML=`<div class="level-art" style="background-image:url(assets/worlds-six-v2.png);background-size:200% 300%;background-position:${i%2*100}% ${Math.floor(i/2)*50}%"><span>${String(i+1).padStart(2,'0')} · ${m[3]}</span></div><div class="level-detail"><strong>${m[0]}</strong><p>${m[1]}</p><p>${r?'最好成绩 '+fmt(r.best):'三星目标 '+fmt(m[4])}</p><p class="map-keepsakes">旅途印记 ${(save.keepsakes?.[i]||[]).length} / 3</p><div class="stars">${r?'✦'.repeat(r.stars)+'✧'.repeat(3-r.stars):'✧ ✧ ✧'}</div></div>`;b.onclick=()=>requestStart(i);grid.append(b);});$('map-dialog').showModal();}
 function syncInput(){const held=(...codes)=>codes.some(c=>heldKeys.has(c)),touch=key=>[...touchPoints.values()].includes(key);input={left:held('ArrowLeft','KeyA')||touch('left'),right:held('ArrowRight','KeyD')||touch('right'),down:held('ArrowDown','KeyS')||touch('down'),attack:held('KeyJ','KeyX')||touch('attack')};}
 function clearInput(){heldKeys.clear();touchPoints.clear();syncInput();queued={jump:false,attack:false};if(game)game.player.jumpBuffer=0;}
 function closeDialogs(){document.querySelectorAll('dialog[open]').forEach(d=>d.close());}
 function start(index){if(!assets||index<0||index>=E.META.length)return;finishOpening();lobbyMotion?.pause();closeDialogs();game=new E.Game(index,selected);game.walkDistance=0;runRecorded=false;particles=[];camera={x:0,y:Math.max(-320,Math.min(370,game.player.y-VH*.6))};mode='play';clearInput();$('home').hidden=true;$('play').hidden=false;$('hud-portrait').src=assets.urls[selected];$('hud-name').textContent=E.HEROES.find(h=>h.id===selected).name;$('level-label').textContent=`${String(index+1).padStart(2,'0')} · ${game.level.name}`;$('star-target').textContent='三星目标 '+fmt(game.level.three);$('hint').textContent='← → 移动 · 空格二段跳 · 按住 J 攻击 · ↓ 下穿 · H 操作说明';canvas.focus();last=performance.now();accumulator=0;schedule();sound('jump');}
 function schedule(){if(!raf&&mode==='play')raf=requestAnimationFrame(frame);}
 function stopFrame(){cancelAnimationFrame(raf);raf=0;clearInput();}
 function pause(){if(mode!=='play'||game.status!=='playing')return;mode='paused';stopFrame();$('pause-dialog').showModal();}
 function resume(){if(mode!=='paused'||portraitPhone())return;$('pause-dialog').close();mode='play';last=performance.now();accumulator=0;canvas.focus();schedule();}
 function home(){stopFrame();closeDialogs();mode='home';$('play').hidden=true;$('home').hidden=false;updateProgress();lobbyMotion?.resume();$('start').focus();}
 function finish(){if(runRecorded)return;runRecorded=true;mode='result';stopFrame();const won=game.status==='won',n=won?E.stars(game.time,game.level):0;
  if(won){save=E.record(save,game.level.index,game.time);persist();sound('win');}
  $('result-eyebrow').textContent=won?'A LITTLE LIGHT, FOUND':'LET’S TRY ANOTHER LITTLE STEP';$('result-stars').textContent=won?'✦'.repeat(n)+'✧'.repeat(3-n):'✧';$('result-title').textContent=won?'恭喜，'+game.level.name+'通关！':'没关系，再试一次。';$('result-copy').textContent=won?`你用时 ${Math.floor(game.time/60)} 分 ${Math.floor(game.time%60)} 秒，获得 ${n} 颗星。三星目标 ${fmt(game.level.three)}，可以重玩刷新纪录，也可以直接体验其他关卡。`:'血量用完了。观察怪物的蓄力动作，也别忘记寻找药水和护盾。';$('result-keepsakes').textContent=`本次找到 ${game.keepsakes.length} / 3 枚${E.KEEPSAKES[game.level.index].name} · 手册已收藏 ${(save.keepsakes?.[game.level.index]||[]).length} / 3，重玩可继续补齐。`;$('result-stats').innerHTML=`<span><b>${fmt(game.time)}</b>冒险用时</span><span><b>${game.gems}</b>收集晶石</span><span><b>${game.kills}</b>击败怪物</span>`;$('next-level').hidden=!won||game.level.index===5;$('result-dialog').showModal();}
 function rounded(x,y,w,h,r,fill,stroke){ctx.beginPath();ctx.roundRect(x,y,w,h,r);if(fill){ctx.fillStyle=fill;ctx.fill();}if(stroke){ctx.strokeStyle=stroke;ctx.stroke();}}
 function diamond(x,y,size,color,angle=0){ctx.save();ctx.translate(x,y);ctx.rotate(angle);ctx.beginPath();ctx.moveTo(0,-size);ctx.lineTo(size*.72,0);ctx.lineTo(0,size);ctx.lineTo(-size*.72,0);ctx.closePath();ctx.fillStyle=color;ctx.fill();ctx.strokeStyle='#fff4dccc';ctx.lineWidth=1.1;ctx.stroke();ctx.beginPath();ctx.moveTo(0,-size);ctx.lineTo(-size*.22,0);ctx.lineTo(0,size);ctx.lineTo(size*.2,-size*.25);ctx.closePath();ctx.fillStyle='#ffffff50';ctx.fill();ctx.restore();}
 function sprite(id,x,y,w,h,dir=1,bob=0,alpha=1,pose=null){const s=assets.sprites[id];if(!s)return;const scale=Math.min(w/s.width,h/s.height),dw=s.width*scale,dh=s.height*scale;ctx.save();ctx.globalAlpha=alpha;ctx.translate(x+w/2,y+h+bob);ctx.scale(E.spriteFlip(id,dir),1);if(pose&&motionRenderer)motionRenderer.draw(ctx,id,-w/2,-h,w,h,pose);else ctx.drawImage(s,-dw/2,-dh,dw,dh);ctx.restore();}
 const pal=[['#cdb8d5','#a8d3cb','#eed6cf'],['#a6d6c5','#7db6b0','#d3ead7'],['#e5bf88','#e6dbb9','#b7dce0']];
 const material=[['#f4c5df','#bc779f'],['#edf7f4','#8ebccc'],['#91d7bd','#438f88'],['#b5a0e8','#69539b'],['#f0c57d','#af7c39'],['#d1ddfa','#8695c8']];
 function platform(p,scene){const [light,dark]=material[scene];ctx.save();if(p.kind==='crumble'&&p.trigger>0){ctx.globalAlpha=.55+Math.sin(game.time*30)*.3;}ctx.shadowColor='#322b5d60';ctx.shadowBlur=6;const r=p.oneWay?12:18;rounded(p.x,p.y,p.w,p.h,r,dark);ctx.save();ctx.beginPath();ctx.roundRect(p.x,p.y,p.w,p.h,r);ctx.clip();const tile=assets.terrain,sh=tile.height/3;ctx.globalAlpha*=.45;ctx.drawImage(tile,0,Math.floor(scene/2)*sh,tile.width,sh,p.x,p.y,p.w,p.h);ctx.globalAlpha=1;const g=ctx.createLinearGradient(0,p.y,0,p.y+p.h);g.addColorStop(0,light+'bb');g.addColorStop(1,dark+'44');ctx.fillStyle=g;ctx.fillRect(p.x,p.y,p.w,p.h);ctx.restore();
  ctx.lineWidth=2;rounded(p.x,p.y,p.w,p.oneWay?14:19,8,light,'#ffeaca');ctx.fillStyle='#fffaf1';ctx.fillRect(p.x+10,p.y+3,p.w-20,2);
  if(scene===0){for(let x=p.x+18;x<p.x+p.w-10;x+=45){ctx.fillStyle='#fff1e0';ctx.beginPath();ctx.arc(x,p.y+18,4,0,Math.PI*2);ctx.fill();}}
  if(scene===1){ctx.strokeStyle='#fff9df';for(let x=p.x+25;x<p.x+p.w-15;x+=55){ctx.beginPath();ctx.arc(x,p.y+17,16,0,Math.PI);ctx.stroke();}}
  if(scene===2){ctx.strokeStyle='#cef5cc';for(let x=p.x+25;x<p.x+p.w-12;x+=65){ctx.beginPath();ctx.moveTo(x,p.y+10);ctx.lineTo(x+18,p.y+25);ctx.lineTo(x+40,p.y+10);ctx.stroke();}}
  if(scene===3){ctx.strokeStyle='#f1d4ff';for(let x=p.x+20;x<p.x+p.w-15;x+=60){ctx.beginPath();ctx.moveTo(x,p.y+2);ctx.lineTo(x+15,p.y+16);ctx.lineTo(x+5,p.y+30);ctx.stroke();}}
  if(scene===4){for(let x=p.x+30;x<p.x+p.w-15;x+=65)diamond(x,p.y+22,7,'#ffe2a2');}
  if(scene===5){ctx.fillStyle='#fff8da';ctx.font='16px Georgia';for(let x=p.x+25;x<p.x+p.w-10;x+=75)ctx.fillText('✧',x,p.y+26);}
  if(p.kind==='crumble'){ctx.strokeStyle='#4e285d';ctx.lineWidth=3;for(let x=p.x+25;x<p.x+p.w-5;x+=42){ctx.beginPath();ctx.moveTo(x,p.y+1);ctx.lineTo(x-7,p.y+10);ctx.lineTo(x+5,p.y+18);ctx.lineTo(x-5,p.y+p.h);ctx.stroke();}}
  if(p.axis){ctx.strokeStyle='#fff7d980';ctx.setLineDash([3,6]);ctx.beginPath();if(p.axis==='y'){ctx.moveTo(p.x+p.w/2,p.origin-p.amplitude);ctx.lineTo(p.x+p.w/2,p.origin+p.amplitude+30);}else{ctx.moveTo(p.origin-p.amplitude,p.y+45);ctx.lineTo(p.origin+p.amplitude+p.w,p.y+45);}ctx.stroke();ctx.setLineDash([]);}
  if(p.oneWay){ctx.strokeStyle='#ffeaca99';if(scene===1){for(let x=p.x+20;x<p.x+p.w-10;x+=35){ctx.beginPath();ctx.arc(x,p.y+p.h-1,11,0,Math.PI);ctx.stroke();}}if(scene===2){for(let x=p.x+30;x<p.x+p.w-10;x+=90){ctx.beginPath();ctx.moveTo(x,p.y+p.h);ctx.quadraticCurveTo(x-15,p.y+55,x+8,p.y+67);ctx.stroke();}}if(scene===3){for(let x=p.x+25;x<p.x+p.w-10;x+=65){ctx.fillStyle='#a58be0bb';ctx.beginPath();ctx.moveTo(x-12,p.y+p.h);ctx.lineTo(x,p.y+p.h+25);ctx.lineTo(x+12,p.y+p.h);ctx.fill();}}if(scene===5){for(let x=p.x+30;x<p.x+p.w-10;x+=85){ctx.beginPath();ctx.moveTo(x,p.y+p.h);ctx.lineTo(x,p.y+60);ctx.stroke();diamond(x,p.y+67,7,'#e8e5ff');}}}
  ctx.restore();
 }
 function drawMechanisms(l,t){for(const d of l.devices){if(d.x+d.w<camera.x||d.x>camera.x+VW)continue;ctx.save();if(d.type==='wind'){const g=ctx.createLinearGradient(0,d.y,0,d.y+d.h);g.addColorStop(0,'#bfffee00');g.addColorStop(1,'#c8fff263');ctx.fillStyle=g;ctx.fillRect(d.x,d.y,d.w,d.h);ctx.strokeStyle='#edfffbbb';ctx.lineWidth=2;for(let i=0;i<5;i++){const y=d.y+d.h-(t*140+i*91)%d.h;ctx.beginPath();ctx.moveTo(d.x+20,y);ctx.quadraticCurveTo(d.x+d.w/2,y-28,d.x+d.w-20,y);ctx.stroke();}}
  if(d.type==='spring'){rounded(d.x,d.y,d.w,d.h,7,'#f3a5d3','#fff5d5');ctx.fillStyle='#fff8dd';ctx.font='bold 18px Georgia';ctx.textAlign='center';ctx.fillText('↑',d.x+d.w/2,d.y-8);}
  if(d.type==='tide'){rounded(d.x,d.y+d.h-10,d.w,10,5,'#85deec','#fff3d1');if(d.active){const g=ctx.createLinearGradient(0,d.y,0,d.y+d.h);g.addColorStop(0,'#d3f9ff33');g.addColorStop(1,'#7edcebea');ctx.fillStyle=g;ctx.fillRect(d.x,d.y,d.w,d.h);ctx.strokeStyle='#f3ffff';for(let k=0;k<5;k++){ctx.beginPath();ctx.moveTo(d.x+12+k*17,d.y+d.h);ctx.quadraticCurveTo(d.x+k*18,d.y+60,d.x+12+k*17,d.y+Math.sin(t*9+k)*14);ctx.stroke();}}else if(d.warning){ctx.fillStyle='#fff0bc';ctx.font='bold 27px Georgia';ctx.textAlign='center';ctx.fillText('!',d.x+d.w/2,d.y+d.h-30);}}
  ctx.restore();}
  for(const sign of l.signs){if(Math.abs(sign.x-camera.x)>VW+100)continue;rounded(sign.x-25,sign.y-65,Math.max(sign.short?190:390,sign.text.length*14+30),52,12,'#382d5dbb','#e5d2a9');ctx.fillStyle='#fff9df';ctx.font='14px Microsoft YaHei';ctx.textAlign='left';ctx.fillText(sign.text,sign.x-10,sign.y-34);}
 }
 function drawItem(i,t){if(i.taken)return;if(i.type==='keepsake'){drawKeepsake(i,t);return;}const y=i.y+Math.sin(t*2.5+i.x)*4;ctx.save();ctx.shadowColor=i.type==='gem'?'#fbdff8':'#fff';ctx.shadowBlur=10;if(i.type==='gem')diamond(i.x,y,12,'#d993be',Math.sin(t+i.x)*.1);else if(i.type==='heal'){rounded(i.x-11,y-11,22,26,7,'#e98fa8','#fff3e7');rounded(i.x-5,y-18,10,9,2,'#b18b59');ctx.fillStyle='#fff7ee';ctx.fillRect(i.x-2,y-6,4,15);ctx.fillRect(i.x-7,y-1,14,4);}else{ctx.beginPath();ctx.moveTo(i.x-14,y-13);ctx.lineTo(i.x+14,y-13);ctx.lineTo(i.x+12,y+7);ctx.quadraticCurveTo(i.x,y+24,i.x-12,y+7);ctx.closePath();ctx.fillStyle='#89cde2';ctx.fill();ctx.strokeStyle='#fff5df';ctx.lineWidth=2;ctx.stroke();ctx.fillStyle='#fff';ctx.font='18px Georgia';ctx.textAlign='center';ctx.fillText('✧',i.x,y+7);}ctx.restore();}
 function keepsakeSymbol(index){const paths=['M0,-5 C-12,-24,12,-24,0,-5 M5,-2 C20,-20,29,0,5,-2 M3,4 C27,5,15,25,3,4 M-3,4 C-15,25,-27,5,-3,4 M-5,-2 C-29,0,-20,-20,-5,-2','M0,20 C-36,-7,-17,-30,0,-21 C17,-30,36,-7,0,20 M0,17 L-12,-16 M0,17 L0,-18 M0,17 L12,-16','M-12,20 C-28,-8,2,-24,19,-20 C24,5,7,26,-12,20 M-15,23 L15,-16 M-7,12 L-12,-3 M1,3 L15,4','M0,-24 L12,0 L0,24 L-12,0 Z M-12,-13 L-22,3 L-12,20 M12,-13 L22,3 L12,20','M0,-23 C6,-12,22,0,19,11 C12,29,-12,29,-19,11 C-22,0,-6,-12,0,-23 Z','M9,-21 C-21,-26,-31,10,-7,22 C5,28,17,18,20,8 C-2,17,-10,-7,9,-21 Z M15,-20 L20,-12 L15,-4 L10,-12 Z'];return `<svg viewBox="-30 -30 60 60" aria-hidden="true"><path d="${paths[index]}" fill="none" stroke="currentColor" stroke-width="3" stroke-linecap="round" stroke-linejoin="round"/></svg>`;}
 function drawKeepsake(item,t){const m=E.KEEPSAKES[game.level.index],y=item.y+Math.sin(t*2+item.slot)*5;ctx.save();ctx.translate(item.x,y);ctx.shadowColor=m.color;ctx.shadowBlur=20;ctx.strokeStyle='#fff4c6';ctx.lineWidth=1.5;ctx.beginPath();ctx.arc(0,0,28,0,Math.PI*2);ctx.stroke();ctx.fillStyle=m.color;ctx.lineWidth=2;
  if(m.shape==='flower'){for(let k=0;k<5;k++){ctx.save();ctx.rotate(k*Math.PI*2/5);ctx.beginPath();ctx.ellipse(0,-10,7,11,0,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.restore();}diamond(0,0,6,'#fff3c7');}
  else if(m.shape==='shell'){ctx.beginPath();ctx.moveTo(0,19);ctx.bezierCurveTo(-36,-7,-17,-30,0,-21);ctx.bezierCurveTo(17,-30,36,-7,0,19);ctx.fill();ctx.stroke();for(const x of [-12,0,12]){ctx.beginPath();ctx.moveTo(0,17);ctx.lineTo(x,-16);ctx.stroke();}}
  else if(m.shape==='leaf'){ctx.beginPath();ctx.moveTo(-12,20);ctx.bezierCurveTo(-28,-8,2,-24,19,-20);ctx.bezierCurveTo(24,5,7,26,-12,20);ctx.fill();ctx.stroke();ctx.beginPath();ctx.moveTo(-15,23);ctx.lineTo(15,-16);ctx.moveTo(-7,12);ctx.lineTo(-12,-3);ctx.moveTo(1,3);ctx.lineTo(15,4);ctx.stroke();}
  else if(m.shape==='crystal'){diamond(-10,4,17,m.color,-.35);diamond(10,4,17,m.color,.35);diamond(0,-4,24,m.color);}
  else if(m.shape==='drop'){ctx.beginPath();ctx.moveTo(0,-23);ctx.bezierCurveTo(6,-12,22,0,19,11);ctx.bezierCurveTo(12,29,-12,29,-19,11);ctx.bezierCurveTo(-22,0,-6,-12,0,-23);ctx.fill();ctx.stroke();diamond(0,6,9,'#fff0be');}
  else{ctx.beginPath();ctx.moveTo(9,-21);ctx.bezierCurveTo(-21,-26,-31,10,-7,22);ctx.bezierCurveTo(5,28,17,18,20,8);ctx.bezierCurveTo(-2,17,-10,-7,9,-21);ctx.fill();ctx.stroke();diamond(15,-12,8,'#fff3bd');}
  ctx.shadowBlur=0;ctx.font='bold 11px Microsoft YaHei';ctx.textAlign='center';ctx.strokeStyle='#44314c';ctx.lineWidth=3;ctx.strokeText('旅途印记',0,-37);ctx.fillStyle='#fff6d6';ctx.fillText('旅途印记',0,-37);ctx.restore();
 }
 function draw(){if(!game||!assets)return;const p=game.player,l=game.level,t=game.time;ctx.clearRect(0,0,VW,VH);
  const bg=assets.worlds,sw=bg.width/2,sh=bg.height/3,bw=VH*sw/sh,progress=camera.x/Math.max(1,l.width-VW),bx=-(bw-VW)*(.10+progress*.8);ctx.drawImage(bg,l.scene%2*sw,Math.floor(l.scene/2)*sh,sw,sh,bx,0,bw,VH);ctx.fillStyle=l.scene===1?'#e3f4e519':'#fff5ee20';ctx.fillRect(0,0,VW,VH);
  for(let i=0;i<(save.effects?20:0);i++){const x=(i*173-t*13-camera.x*.15)%(VW+40),y=(i*79+t*7)%(VH-20);ctx.fillStyle='#fff7dfaa';ctx.beginPath();ctx.arc(x,y,1+(i%3)*.5,0,Math.PI*2);ctx.fill();}
  ctx.save();ctx.translate(-camera.x,-camera.y);
  drawMechanisms(l,t);for(const plat of l.platforms)if(!plat.gone&&plat.x+plat.w>camera.x-10&&plat.x<camera.x+VW+10)platform(plat,l.scene);
  for(let i=0;i<l.checkpoints.length;i++){const c=l.checkpoints[i];ctx.fillStyle='#b69774';ctx.fillRect(c.x+8,c.y+25,4,40);diamond(c.x+10,c.y+18,12,i<=game.checkpoint?'#ffe8aa':'#b4bbc6');}
  for(const item of game.items)if(item.x>camera.x-30&&item.x<camera.x+VW+30)drawItem(item,t);
  const goal=l.goal;ctx.save();ctx.shadowColor='#fff4c5';ctx.shadowBlur=25;ctx.strokeStyle='#f7dea5';ctx.lineWidth=8;ctx.beginPath();ctx.moveTo(goal.x,goal.y+goal.h);ctx.lineTo(goal.x,goal.y+35);ctx.bezierCurveTo(goal.x,goal.y-13,goal.x+goal.w,goal.y-13,goal.x+goal.w,goal.y+35);ctx.lineTo(goal.x+goal.w,goal.y+goal.h);ctx.stroke();ctx.fillStyle='#fff4d252';ctx.fillRect(goal.x+5,goal.y+30,goal.w-10,goal.h-30);diamond(goal.x+goal.w/2,goal.y+43+Math.sin(t*3)*4,13,'#fff1b7');ctx.font='bold 19px Microsoft YaHei';ctx.textAlign='center';ctx.fillStyle='#fffbe8';ctx.fillText('终点 · 珠光之门',goal.x+goal.w/2,goal.y-22);ctx.restore();
  for(const e of game.enemies){if(e.x+e.w<camera.x-80||e.x>camera.x+VW+80)continue;const moving=e.state==='patrol'||(e.kind==='charge'&&e.state==='attack'),bob=moving?Math.sin(t*10+e.x)*2:0;sprite(e.type,e.x-10,e.y-7,e.w+20,e.h+7,e.dir,bob,e.flash>0?.55:1);if(e.hp<e.maxHp||e.state!=='patrol'){rounded(e.x,e.y-15,e.w,4,3,'#73677788');rounded(e.x,e.y-15,e.w*e.hp/e.maxHp,4,3,'#c47f96');}if(e.state==='windup'){ctx.font='bold 27px Georgia';ctx.textAlign='center';ctx.strokeStyle='#473047';ctx.lineWidth=4;ctx.strokeText('!',e.x+e.w/2,e.y-27);ctx.fillStyle='#fff0a8';ctx.fillText('!',e.x+e.w/2,e.y-27);}if(e.type==='11'){ctx.font='12px Microsoft YaHei';ctx.fillStyle='#fff6df';ctx.textAlign='center';ctx.fillText('↓ 踩踏破甲',e.x+e.w/2,e.y-42);}if(e.tier===2)diamond(e.x+e.w/2,e.y-24,5,'#a85d85');}
  for(const b of game.projectiles){ctx.save();const x=b.x+b.w/2,y=b.y+b.h/2;ctx.shadowBlur=16;
   if(b.owner==='player'){ctx.shadowColor='#fff2bf';ctx.lineWidth=9;const trail=ctx.createLinearGradient(x-b.vx*.095,y,x,y);trail.addColorStop(0,'#fbb0fa00');trail.addColorStop(1,'#fff8df');ctx.strokeStyle=trail;ctx.beginPath();ctx.moveTo(x-b.vx*.095,y);ctx.lineTo(x,y);ctx.stroke();diamond(x,y,13,'#fff8d7',t*5);}
   else if(b.type==='spike'){ctx.shadowColor='#ea95fb';ctx.translate(x,y);ctx.rotate(Math.atan2(b.vy,b.vx)+Math.PI/2);ctx.scale(.72,1.4);diamond(0,0,12,'#d894ec');ctx.strokeStyle='#fff3c5';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(0,7);ctx.lineTo(0,22);ctx.stroke();}
   else if(b.type==='wave'){ctx.shadowColor='#d7a3fa';ctx.fillStyle='#a95be95c';ctx.strokeStyle='#f7d6ff';ctx.lineWidth=4;ctx.beginPath();ctx.ellipse(x,y,b.w*.56,b.h*.6,0,Math.PI,Math.PI*2);ctx.lineTo(x+b.w*.56,y+b.h*.35);ctx.lineTo(x-b.w*.56,y+b.h*.35);ctx.closePath();ctx.fill();ctx.stroke();ctx.strokeStyle='#fff4bc';ctx.lineWidth=2;ctx.beginPath();ctx.ellipse(x,y+3,b.w*.34,b.h*.35,0,Math.PI,Math.PI*2);ctx.stroke();}
   else{ctx.shadowColor='#91d8e9';ctx.beginPath();ctx.ellipse(x,y,b.w/2,b.h/2,0,0,Math.PI*2);ctx.fillStyle='#83ceeede';ctx.fill();ctx.strokeStyle='#edffff';ctx.lineWidth=2;ctx.stroke();ctx.fillStyle='#ffffffcc';ctx.beginPath();ctx.arc(b.x+b.w*.35,b.y+b.h*.3,3,0,Math.PI*2);ctx.fill();}
   ctx.restore();}
  const heroWidth=selected==='12'?95:selected==='03'?74:82,heroHeight=selected==='12'?70:91,bob=0,action=!p.grounded?(p.vy<0?'jump':'fall'):Math.abs(p.vx)>20?'walk':p.attackFlash>0?'attack':'idle',motionPose={action,attack:p.attackFlash>0,phase:action==='walk'?game.walkDistance/70*Math.PI*2:t*2,strength:Math.min(1,Math.abs(p.vx)/290),reduced:save.reducedMotion||matchMedia('(prefers-reduced-motion:reduce)').matches};
  heroMotion=motionPose;ctx.save();if(p.attackFlash>0){ctx.shadowColor='#fff4b5';ctx.shadowBlur=24;}sprite(selected,p.x+p.w/2-heroWidth/2,p.y+p.h-heroHeight,heroWidth,heroHeight,p.facing,bob,p.invuln>0&&Math.floor(t*14)%2===0?.45:1,motionPose);ctx.restore();
  if(p.attackFlash>0){ctx.save();ctx.translate(p.x+p.w/2+p.facing*36,p.y+35);ctx.scale(p.facing,1);ctx.globalAlpha=p.attackFlash/.18;ctx.strokeStyle='#fffce3';ctx.shadowColor='#ffc9ef';ctx.shadowBlur=28;ctx.lineWidth=5;ctx.beginPath();ctx.arc(0,0,20+(1-p.attackFlash/.18)*35,-1.3,1.3);ctx.stroke();for(let i=0;i<5;i++)diamond(16+i*10,(i-2)*9,5,'#fff8da');ctx.restore();}
  if(p.shield>0){ctx.save();ctx.strokeStyle='#c8f2ffe0';ctx.lineWidth=2;ctx.fillStyle='#a0e4f521';ctx.shadowColor='#bcf5ff';ctx.shadowBlur=15;ctx.beginPath();ctx.arc(p.x+p.w/2,p.y+p.h/2-6,53,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.restore();}
  for(const e of game.effects){for(let i=0;i<8;i++){const a=i*Math.PI/4,r=(1-e.life/e.max)*48;ctx.globalAlpha=e.life/e.max;diamond(e.x+Math.cos(a)*r,e.y+Math.sin(a)*r,5,e.color);}}ctx.globalAlpha=1;
  for(const a of particles){ctx.globalAlpha=Math.max(0,a.life/a.max);if(a.text){ctx.font='14px Microsoft YaHei';ctx.fillStyle=a.color;ctx.textAlign='center';ctx.fillText(a.text,a.x,a.y);}else diamond(a.x,a.y,a.size,a.color);}ctx.globalAlpha=1;
  ctx.restore();if(p.hp<=25){ctx.strokeStyle='#e1889988';ctx.lineWidth=12;ctx.strokeRect(6,6,VW-12,VH-12);}
 }
 function handleEvents(){for(const e of game.events){sound(e.type);if(e.type==='keepsake'){save=E.rememberKeepsake(save,game.level.index,e.value);persist();toast('找到'+E.KEEPSAKES[game.level.index].name+' · 已收入旅人手册');for(let j=0;j<14;j++)particles.push({x:e.x,y:e.y,life:.8,max:.8,vx:Math.cos(j)*100,vy:Math.sin(j)*100,size:5,color:E.KEEPSAKES[game.level.index].color});}const text={heal:'+35 血量',shield:'护盾 · 6 秒',hurt:'−'+Number(e.value?.toFixed(1)),fall:'−20',checkpoint:'灯塔已点亮',block:'护盾抵挡'}[e.type];if(text)particles.push({x:e.x,y:e.y-15,life:1.1,max:1.1,color:e.type==='hurt'?'#a94666':'#6a617c',text});if(e.type==='hit'||e.type==='stomp')for(let j=0;j<10;j++)particles.push({x:e.x+25,y:e.y+20,life:.4,max:.4,vx:Math.cos(j)*170,vy:Math.sin(j)*170,size:5,color:'#fff2bc'});if(e.type==='gem'&&save.effects)for(let j=0;j<5;j++)particles.push({x:e.x,y:e.y,life:.5,max:.5,vx:(j-2)*50,vy:-60-j*12,size:3,color:'#f3d4ef'});if(e.type==='armor'&&!particles.some(p=>p.text==='向上跳，踩踏破甲'))particles.push({x:e.x,y:e.y-20,life:1,max:1,color:'#fff4cc',text:'向上跳，踩踏破甲'});if(e.type==='checkpoint')toast('灯塔已点亮，跌落后会回到这里。');if(e.type==='fall'){camera.x=Math.max(0,game.player.x-300);camera.y=280;}}game.events=[];}
 function hud(){const p=game.player;$('hp-label').textContent=Math.ceil(p.hp)+' / 100';$('hp-fill').style.width=p.hp+'%';document.querySelector('.health-track').setAttribute('aria-valuenow',Math.ceil(p.hp));$('shield-label').textContent=p.shield>0?'护盾保护 · '+Math.ceil(p.shield)+' 秒':'星光会为你指路';$('timer').textContent=fmt(game.time);const target=game.time<=game.level.three?['三星',game.level.three]:game.time<=game.level.two?['两星',game.level.two]:null;$('star-target').textContent=target?target[0]+'还余 '+fmt(Math.max(0,target[1]-game.time)):'一星 · 到达终点即可完成';const progress=game.status==='won'?100:Math.min(99,Math.floor(p.x/game.level.goal.x*100));$('route-fill').style.width=progress+'%';$('route-progress').setAttribute('aria-valuenow',progress);$('route-progress').setAttribute('aria-valuetext','已前进 '+progress+'%');$('route-label').textContent=progress+'%';$('gems').textContent=game.gems;$('keepsake-count').textContent=game.keepsakes.length+' / 3';$('keepsake-progress').title=E.KEEPSAKES[game.level.index].name+'：'+E.KEEPSAKES[game.level.index].hint;const attackButton=document.querySelector('[data-control="attack"]');attackButton.style.setProperty('--attack-ready',Math.round((1-p.cooldown/.34)*100)+'%');$('hint').textContent=game.player.x>game.level.width-950?'前方是终点 · 走入发光拱门完成旅程 · H 操作说明':'← → 移动 · 空格二段跳 · 按住 J 攻击 · ↓ 下穿 · H 操作说明';}
 function frame(now){raf=0;if(mode!=='play')return;accumulator+=Math.min(.1,(now-last)/1000);last=now;while(accumulator>=1/120){const oldX=game.player.x;game.step(1/120,{...input,jump:queued.jump,attack:input.attack||queued.attack});game.walkDistance+=Math.min(10,Math.abs(game.player.x-oldX));queued={jump:false,attack:false};accumulator-=1/120;for(const p of particles){p.life-=1/120;p.y+=(p.vy||-28)/120;p.x+=(p.vx||0)/120;}particles=particles.filter(p=>p.life>0);handleEvents();if(game.status!=='playing')break;}
  camera.x+=(Math.max(0,Math.min(game.level.width-VW,game.player.x-VW*.28))-camera.x)*.10;camera.y+=(Math.max(-320,Math.min(370,game.player.y-VH*.60))-camera.y)*.08;draw();hud();if(game.status!=='playing')finish();else schedule();}
 let helpReturn='home',pendingLevel=0,mapReturn='home';
 function closeMap(){$('map-dialog').close();mode=mapReturn;}
 const mechanismGuide=[['弹簧花与花阶','踩上粉色弹簧花会向上弹起，空中还可以再跳一次。沿连续花阶登上长廊，上层能找到更多晶石。'],['贝壳升降台','带有竖向轨迹的贝壳台会自动升降。站稳后随台移动，再跳向邻近水廊；按 ↓ 可以提前下穿。'],['瀑谷上升气流','进入带有向上流动白线的风柱，会被托向高处。左右移动可离开气流，留意栈道上的远程守卫。'],['碎裂晶桥','带明显裂纹的短桥踩上后约半秒就会破碎。及时跳到下一块；桥会在几秒后恢复，可以重新尝试。'],['潮汐喷泉','喷口上方的感叹号是喷水预警。先在喷口外等待，水柱落下后再通过，或走较高的礁石路线。'],['星链渡台','中段有一处必须搭乘宽渡台的星河。等它靠岸后跳上，站稳随它前进，到对岸再走下。两岸的灯塔会保存落脚点。']];
 function requestStart(index){if(!assets?.worlds)return;if(!save.tutorialSeen){pendingLevel=index;openHelp('start');}else start(index);}
 function openHelp(origin=mode){helpReturn=origin;if(origin==='start')$('tutorial-skip').checked=false;if(origin==='play'){mode='help';stopFrame();}if(origin==='paused'){mode='help';$('pause-dialog').close();}$('tutorial-preference').hidden=origin!=='start';$('help-confirm').textContent=origin==='start'?'明白了，开始冒险 →':origin==='play'?'继续冒险':'记住了';$('help-context').textContent=origin==='start'?`即将进入「${E.META[pendingLevel][0]}」 · ${E.META[pendingLevel][1]}。确认后才开始计时。`:'游戏中按 H 或点击右上角 ? 随时查看，查看说明时计时暂停。';const levelIndex=origin==='start'?pendingLevel:game?.level.index;const brief=$('help-mechanic');brief.hidden=origin==='home'||levelIndex===undefined;if(!brief.hidden){$('mechanic-title').textContent=mechanismGuide[levelIndex][0];$('mechanic-copy').textContent=mechanismGuide[levelIndex][1]+' 本关有三枚'+E.KEEPSAKES[levelIndex].name+'。'+E.KEEPSAKES[levelIndex].hint+' 收到后自动保存在旅人手册，失败或退出也会保留；印记不影响时间星级。';}$('help-dialog').showModal();}
 function closeHelp(confirm=false){$('help-dialog').close();if(helpReturn==='start'){if(confirm){save.tutorialSeen=$('tutorial-skip').checked;persist();applyPreferences();start(pendingLevel);}}else if(helpReturn==='play'){mode='paused';if(portraitPhone())$('pause-dialog').showModal();else resume();}else if(helpReturn==='paused'){mode='paused';$('pause-dialog').showModal();}}
 $('start').onclick=()=>requestStart(0);$('open-map').onclick=showMap;$('pause-map').onclick=showMap;$('result-map').onclick=showMap;$('help-home').onclick=()=>openHelp('home');$('help-play').onclick=()=>openHelp('play');$('help-paused').onclick=()=>openHelp('paused');$('help-confirm').onclick=()=>closeHelp(true);$('pause').onclick=pause;$('resume').onclick=resume;$('restart').onclick=()=>start(game.level.index);$('back-home').onclick=home;$('next-level').onclick=()=>requestStart(game.level.index+1);$('retry-result').onclick=()=>start(game.level.index);$('result-home').onclick=home;
 document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>b.closest('dialog').id==='help-dialog'?closeHelp():b.closest('dialog').id==='map-dialog'?closeMap():b.closest('dialog').close());$('map-dialog').addEventListener('cancel',e=>{e.preventDefault();closeMap();});$('help-dialog').addEventListener('cancel',e=>{e.preventDefault();closeHelp();});$('pause-dialog').addEventListener('cancel',e=>{e.preventDefault();resume();});$('result-dialog').addEventListener('cancel',e=>{e.preventDefault();home();});
 window.addEventListener('keydown',e=>{if(mode==='paused'){if(e.code==='KeyP'&&!e.repeat){e.preventDefault();resume();}return;}if(mode!=='play')return;const codes=['ArrowLeft','ArrowRight','ArrowUp','ArrowDown','Space','KeyA','KeyD','KeyW','KeyS','KeyJ','KeyX','KeyP','Escape','KeyH','F1'];if(!codes.includes(e.code))return;e.preventDefault();if(e.repeat&&['KeyP','Escape','KeyH','F1'].includes(e.code))return;if(e.code==='KeyH'||e.code==='F1'){openHelp('play');return;}if(e.code==='KeyP'||e.code==='Escape'){pause();return;}heldKeys.add(e.code);syncInput();if(!e.repeat&&['Space','ArrowUp','KeyW'].includes(e.code))queued.jump=true;if(!e.repeat&&['KeyJ','KeyX'].includes(e.code))queued.attack=true;});
 window.addEventListener('keyup',e=>{heldKeys.delete(e.code);syncInput();});
 document.querySelectorAll('[data-control]').forEach(b=>{const key=b.dataset.control;const release=e=>{touchPoints.delete(e.pointerId);syncInput();};b.addEventListener('pointerdown',e=>{e.preventDefault();if(mode!=='play')return;b.setPointerCapture(e.pointerId);touchPoints.set(e.pointerId,key);syncInput();if(key==='jump'||key==='attack')queued[key]=true;});b.addEventListener('pointerup',release);b.addEventListener('pointercancel',release);b.addEventListener('lostpointercapture',release);});
 window.addEventListener('blur',()=>{if(mode==='play')pause();else clearInput();});document.addEventListener('visibilitychange',()=>{if(document.hidden)pause();});window.addEventListener('message',e=>{if(e.source===window.parent&&e.origin===location.origin&&e.data?.type==='portfolio-game-pause')pause();});
 function buildParty(){const host=$('lobby-party');host.textContent='';E.HEROES.filter(h=>h.id!==selected).forEach((h,i)=>{const b=document.createElement('button');b.className='party-member party-'+i;b.dataset.hero=h.id;b.style.setProperty('--i',i);b.style.setProperty('--entry-order',E.HEROES.findIndex(hero=>hero.id===h.id));b.setAttribute('aria-label','与'+h.name+'同行');b.innerHTML=`<canvas width="300" height="340" aria-hidden="true"></canvas><span>${h.name}</span>`;b.onclick=e=>{choose(h.id);burst(e.clientX,e.clientY);toast(h.line);sound('gem');};host.append(b);});}
 function applyPreferences(){lobbyMotion?.refresh();document.body.classList.toggle('reduced-motion',save.reducedMotion);$('home').classList.toggle('reduced-motion',save.reducedMotion);document.body.classList.toggle('no-effects',!save.effects);$('music-enabled').checked=save.music;$('sfx-enabled').checked=save.sound;$('master-volume').value=Math.round(save.volume*100);$('reduce-motion').checked=save.reducedMotion;$('show-effects').checked=save.effects;$('show-tutorial').checked=!save.tutorialSeen;window.SpiritAudio.sync(save);$('music-status').textContent=save.music?(window.SpiritAudio.unlocked?'♫ 庭院旋律正在轻轻流动':'点击后唤醒庭院音乐 · 可在声音中关闭'):'♫ 庭院音乐已关闭';}
 function burst(x,y){if(!save.effects||save.reducedMotion)return;const box=$('home').getBoundingClientRect();for(let i=0;i<7;i++){const a=document.createElement('span');a.className='lobby-spark';a.textContent=i%2?'✧':'✦';a.style.cssText=`left:${x-box.left}px;top:${y-box.top}px;--dx:${Math.cos(i)*60}px;--dy:${Math.sin(i)*60-20}px`;$('lobby-sparks').append(a);setTimeout(()=>a.remove(),900);}}
 let unlocking=false;const unlock=async()=>{if(!window.SpiritAudio.unlocked&&!unlocking){unlocking=true;await window.SpiritAudio.unlock(save);applyPreferences();unlocking=false;}};document.addEventListener('pointerdown',unlock);document.addEventListener('keydown',unlock);
 for(const id of ['notice','sound','settings','account'])$('open-'+id).onclick=()=>{if(id==='account'){$('nickname').value=save.nickname;$('profile-stats').innerHTML=`<span><b>${save.records.filter(Boolean).length} / 6</b>已完成关卡</span><span><b>${save.records.reduce((n,r)=>n+(r?.stars||0),0)} / 18</b>旅途之星</span>`;$('collection-grid').innerHTML=E.KEEPSAKES.map((m,i)=>{const found=save.keepsakes?.[i]||[];return `<div class="collection-card"><b>${m.name}</b><span aria-label="已收藏 ${found.length} 枚，共 3 枚">${[0,1,2].map(slot=>`<i class="${found.includes(slot)?'found':''}" title="第 ${slot+1} 枚${found.includes(slot)?' · 已收藏':' · 待寻找'}" style="--stamp-color:${m.color}">${keepsakeSymbol(i)}</i>`).join('')}</span><small>${E.META[i][0]} · ${found.length} / 3</small></div>`;}).join('');const archive=$('legacy-records');archive.textContent=save.legacyRecords?.some(Boolean)?'旧版短关成绩（已归档）：'+save.legacyRecords.map((r,i)=>r?`${i+1}关 ${fmt(r.best)} / ${r.stars}星`:null).filter(Boolean).join(' · '):'';if(save.legacyMoonRecord)archive.textContent+=' 月光浮岛旧路线（渡台更新前）：'+fmt(save.legacyMoonRecord.best)+' / '+save.legacyMoonRecord.stars+' 星。';}$(id+'-dialog').showModal();};
 $('notice-preview').onclick=()=>$('notice-dialog').showModal();
 [['music-enabled','music'],['sfx-enabled','sound'],['reduce-motion','reducedMotion'],['show-effects','effects']].forEach(([id,key])=>$(id).onchange=()=>{save[key]=$(id).checked;persist();applyPreferences();});
 $('master-volume').oninput=()=>{save.volume=Number($('master-volume').value)/100;persist();applyPreferences();};
 $('show-tutorial').onchange=()=>{save.tutorialSeen=!$('show-tutorial').checked;persist();};
 $('save-profile').onclick=()=>{save.nickname=Array.from($('nickname').value.trim()||'珠光旅人').slice(0,16).join('');persist();$('account-dialog').close();toast(save.nickname+'，欢迎回到庭院。');};
 $('fullscreen').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen();}catch{toast('当前浏览器未开放全屏，可使用“打开横屏游戏”独立游玩。');}};
 let trailAt=0;$('home').addEventListener('pointermove',e=>{if(save.reducedMotion)return;$('home').style.setProperty('--mx',(e.clientX/innerWidth-.5)*12+'px');$('home').style.setProperty('--my',(e.clientY/innerHeight-.5)*8+'px');if(performance.now()-trailAt>140){burst(e.clientX,e.clientY);trailAt=performance.now();}});
 $('featured').onclick=e=>{burst(e.clientX,e.clientY);toast(E.HEROES.find(h=>h.id===selected).line);sound('gem');};
 $('rotate-dialog').addEventListener('cancel',e=>e.preventDefault());applyPreferences();updateProgress();
 window.SpiritAssets.load((n,label)=>{$('loading-label').textContent=label;$('loading-percent').textContent=n+'%';$('loading-fill').style.width=n+'%';document.querySelector('.loading-track').setAttribute('aria-valuenow',n);},a=>{assets=a;motionRenderer=SpiritMotion.createRenderer(a.sprites);buildHeroes();lobbyMotion=SpiritLobby.create({stage:document.querySelector('.character-stage'),renderer:motionRenderer,heroes:E.HEROES,nativeFacing:E.NATIVE_FACING,getSelected:()=>selected,getPreferences:()=>save});opening();}).then(a=>{assets=a;$('loading-panel').hidden=true;$('home').classList.remove('is-loading');for(const id of ['start','open-map']){$(id).disabled=false;$(id).hidden=false;}}).catch(err=>{$('loading-label').textContent='素材加载失败，请刷新重试';toast(err.message);console.error(err);});
 if(new URLSearchParams(location.search).get('test')==='1')window.__spiritTest={get game(){return game;},get mode(){return mode;},get save(){return save;},get assets(){return assets;},get motion(){return motionRenderer;},get heroMotion(){return heroMotion;},get lobby(){return lobbyMotion?.state;},replayEntrance:()=>lobbyMotion?.start(),pauseLobby:()=>lobbyMotion?.pause(),start,requestStart,openHelp,pause,resume,home,choose,draw,finish,step(dt,i){game.step(dt,i);handleEvents();draw();hud();if(game.status!=='playing')finish();}};
})();
